# Generated by Django 3.1.3 on 2021-01-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sit', '0001_initial'),
        ('domaine', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domaine',
            field=models.ManyToManyField(to='domaine.Domaine'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sites', to='sit.sit'),
        ),
    ]
